#!/usr/bin/env ruby
require_relative 'src/knight'

if $*.length != 2 || !%w[-e -f].include?($*.first)
	abort "usage: #$0 (-e 'program' | -f file)"
end

program = $*.shift == '-e' ? $*.shift : File.read($*.shift)
Knight.run(program)
