module Knight
  # The array type within Knight.
  class ListLiteral < Value
    @vals: __todo__

    # Parses a List out from the stream.
    def self.parse: (__todo__ stream) -> (nil | __todo__)

    def initialize: (__todo__ vals) -> void

    def run: () -> __todo__
  end
end
