module Knight
  # The array type within Knight.
  class ListLiteral < Value
    @vals: untyped

    # Parses a List out from the stream.
    def self.parse: (untyped stream) -> (nil | untyped)

    def initialize: (untyped vals) -> void

    def run: () -> untyped
  end
end
