module Knight
  $_FUNCS: Hash[String, __todo__]
  # Used to represent functions and their arguments within Knight.
  class Ast < Value
    @func: __todo__

    @name: __todo__

    @args: __todo__

    # Parses a `Ast` from the stream, returning `None` if the
    # stream didn't start with a function character.
    #
    # This will both parse the function name, and its arguments. If not
    # all the arguments could be parsed, a `ParseError` is raised.
    def self.parse: (Stream stream) -> instance?

    # Creates a new function that'll execute `func` with `args`.
    #
    # Note that the `name` is only used for `__repr__`.
    def initialize: (__todo__ func, __todo__ name, __todo__ args) -> void

    def run: () -> Value

    def inspect: () -> String
  end

  # Used to register a new function with the given name.
  #
  # If no name is supplied, it will use the upper-case version of the
  # first letter of the function's name.
  def self?.register: (__todo__ name) -> __todo__
                    | (__todo__ which, __todo__ name) -> __todo__
end
