module Knight
  class Boolean < Literal[bool]
    def self.parse: (Stream stream) -> instance?

    TRUE: instance
    FALSE: instance

    def self.new: (boolish) -> instance

    def truthy?: () -> boolish
    def to_i: () -> (1 | 0)
    def to_a: () -> (Array[self] | [])
    alias == equal?

    def <=>: (__todo__ other) -> Integer?

    def +: (_Truthy other) -> Boolean
    def *: (_Truthy other) -> Boolean
  end
end
