module Knight
  # The Basic numeric class within Knight.
  #
  # As per the Knight specs, the only number type is an integer, which this class represents. However,
  # as an extension, other types are also accepted as long as the option is set.
  class Int < Literal[Integer]
    # Parses a Number out from the stream.
    # This returns `None` if the stream doesn't start with a digit.
    def self.parse: (untyped stream) -> untyped

    # Returns whether `self` is nonzero.
    def truthy?: () -> untyped

    # Returns the digits in `self`
    def to_a: () -> untyped

    # Converts `rhs` to an `Int` and adds it to `self.`
    def +: (untyped rhs) -> untyped

    # Converts `rhs` to an `Int` and subtracts it from `self.`
    def -: (untyped rhs) -> untyped

    # Converts `rhs` to an `Int` and multiples it by it `self.`
    def *: (untyped rhs) -> untyped

    # Converts `rhs` to an `int` and divides `self` by it, with the
    # division operation conforming to the Knight specs.
    #
    # This will raise a `RunError` if `rhs` is zero.
    def /: (untyped rhs) -> untyped

    # Converts `rhs` to an `int` and modulos `self` by it, with the
    # modulo operation conforming to the Knight specs.
    #
    # This will raise a `RunError` if `rhs` is zero.
    def %: (untyped rhs) -> untyped

    # Converts `rhs` to an `int` and exponentiates `self` by it, with
    # the power of operation conforming to the Knight specs.
    def **: (untyped rhs) -> untyped

    def <=>: (untyped rhs) -> untyped
  end
end
