module Knight
  # The array type within Knight.
  class List < Literal[Array[Value]]
    # Parses a List out from the stream.
    def self.parse: (__todo__ stream) -> __todo__

    # Converting a `List` to a string is done by joining it with newlines
    def to_s: () -> __todo__

    # The integer representation of a `List` is its element count
    def to_i: () -> __todo__

    # The array representation of `List` is simply its data
    def to_a: () -> __todo__

    # A List is truthy when it's not empty.
    def truthy?: () -> __todo__

    # Adding to a list converts `rhs` to list and concatenates teh two.
    def +: (__todo__ rhs) -> __todo__

    # Repeats the list by `amount` times
    def *: (__todo__ amount) -> __todo__

    # Joins the list by interspersing `sep` between its elements
    def join: (__todo__ sep) -> __todo__

    # `**` is used within Knight
    alias ** join

    # Compares `self` vs `other`, returning `nil` if `other` isn't convertible to an array.
    def <=>: (__todo__ other) -> (__todo__ | nil)

    # Gets the value at `index`, using the same indexing operations as `Array`s. If the result is an
    # array, it's converted to a `List`.
    def []: (*__todo__) ?{ (?) -> __todo__ } -> __todo__
  end
end
