module Knight
  class Null < Literal[nil]
    def self.parse: (Stream stream) -> instance?

    INSTANCE: instance

    def self.new: () -> instance

    def to_i: () -> 0

    # :nodoc:
    EMPTY_ARRAY: Array[Value]

    def to_a: () -> []

    def to_s: () -> ''

    def truthy?: () -> false

    def inspect: () -> 'null'

    alias == equal?
  end
end
