# The class used when parsing data.
class Stream
  @source: String
  @position: Integer

  # Creates a new `Stream` with the given source.
  def initialize: (String source) -> void

  # Returns whether the stream is empty.
  def empty?: () -> bool

  # Removes all leading whitespace and quotes
  def strip_whitespace_and_comments!: () -> void

  # Raises a parsing message at the given location
  def raise: (String msg) -> bot

  # Returns the first character of the stream
  def peek: () -> String?

  # Checks to see if the start of the stream matches `rxp`.
  #
  # If the stream doesn't match, `None` is returned. Otherwise, the
  # stream is updated, and the `index`th group is returned. (The
  # default value of `0` means the entire matched regex is returned.)
  def matches: (Regexp regex, ?Integer index) -> String?

  def matches!: (Regexp regex, ?Integer index) -> String?
end
