module Knight
  # Represents an Variable within Knight.
  #
  # Because all Variables in Knight are global---and don't go out of
  # scope---we have a single dict that keeps track of _all_ Variables.
  class Variable < Value
    @name: String
    @value: Value?

    self.@variables: Hash[String, Variable]

    # Parses an Variable out from the stream.
    #
    # This returns `None` if the stream doesn't start with a lowercase
    # letter, or an underscore.
    def self.parse: (Stream stream) -> instance?

    def self.new: (String name) -> instance

    def initialize: (String name) -> void

    def inspect: () -> String

    def run: () -> Value

    def assign: (Value value) -> void
  end
end
